#- name: Demo
#  hosts: localhost
#  tasks:
#    - name: printing hello world in ansible
#      ansible.builtin.debug:
#        msg: hello world

#
#- name: Demo on vars
#  hosts: localhost
#  vars: # variable our define( you can define here everything will access)
#    url: amazon.com
#  tasks:
#    - name: print variable
#      ansible.builtin.debug:
#        msg: "{{url}}" #given the variable in double quotes , because it will fail some cases if cotes are not provided

#Givven the variable in double quotes, ggod to give variable in double quotes , because it will fail some scenarios if codes are not provided.
# in the key : value , if the value is variable or if value start with variable then it will fail'
#
#- name: Demo on task level vars
#  hosts: localhost
#  tasks:
#    - name: print variable
#      ansible.builtin.debug:
#        msg: "{{url}}"
#      vars: # variable our define task level(you can define here it will only access)
#          url: amazon.com


- name: Demo on task level vars
  hosts: localhost
  vars:
    url: play.amazon.com #it is play level
  tasks:
    - name: print task variable
      ansible.builtin.debug:
        msg: "{{url}}"
      vars: # variable our define task level(you can define here it will only access)
        url: task.amazon.com
    - name: print play variable
      ansible.builtin.debug:
        msg: "{{url}}"



#
#- name: demo on printing
#  hosts: localhost
#  tasks:
#    - name: print hello world
#      ansible.builtin.debug:
#        msg: hello world
#
##how to declare a variable
#- name: demo on vars
#  hosts: localhost
#  vars: #defineing the variable
#    URL: example.com
#  tasks:
#    - name: print a variable
#      ansible.builtin.debug:
#        msg: "{{ URL }}"
#
##Givven the variable in double quotes, ggod to give variable in double quotes , because it will fail some scenarios if codes are not provided.
## in the key : value , if the value is variable or if value start with variable then it will fail'
#
## declare variable in task level also
#- name: demo on task leval  vars
#  hosts: localhost
#  vars: #defineing the variable
#    URL: play.example.com
#  tasks:
#    - name: print task variable
#      ansible.builtin.debug:
#        msg: "{{ URL }}"
#      vars: #defineing the variable task level
#        URL: task.example.com
#
#    - name: print play variable
#      ansible.builtin.debug:
#        msg: "{{ URL }}"





